<a href="https://colab.research.google.com/github/aniray2908/ML-foundations-rebuild/blob/main/linear_algebra/eigen_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Eigenvalues & Eigenvectors – Intuition and Computation

Week 1 – Linear Algebra Foundations

Goal:
- Understand eigenvectors geometrically
- Compute eigenvalues/eigenvectors
- Verify Av = λv
- Connect eigenvalues to ML


In [1]:
import numpy as np

### PART 1 — Start With a Simple Matrix

In [2]:
A = np.array([[3, 1],
              [0, 2]])

print("Matrix A:\n", A)

Matrix A:
 [[3 1]
 [0 2]]


### PART 2 — Compute Eigenvalues and Eigenvectors

In [3]:
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:\n", eigenvalues)
print("\nEigenvectors (columns):\n", eigenvectors)

Eigenvalues:
 [3. 2.]

Eigenvectors (columns):
 [[ 1.         -0.70710678]
 [ 0.          0.70710678]]


### PART 3 — Verify the Definition

We now verify:


Av=λv

In [4]:
for i in range(len(eigenvalues)):
    v = eigenvectors[:, i]
    lambda_val = eigenvalues[i]

    Av = A @ v
    lambda_v = lambda_val * v

    print(f"\nEigenvalue {i+1}: {lambda_val}")
    print("Av =", Av)
    print("λv =", lambda_v)


Eigenvalue 1: 3.0
Av = [3. 0.]
λv = [3. 0.]

Eigenvalue 2: 2.0
Av = [-1.41421356  1.41421356]
λv = [-1.41421356  1.41421356]


### PART 4 — Geometric Intuition

In [5]:
random_vector = np.array([1, 1])

transformed = A @ random_vector

print("Original vector:", random_vector)
print("Transformed vector:", transformed)

Original vector: [1 1]
Transformed vector: [4 2]


In [6]:
v = eigenvectors[:, 0]

transformed_eigen = A @ v

print("Eigenvector:", v)
print("Transformed eigenvector:", transformed_eigen)

Eigenvector: [1. 0.]
Transformed eigenvector: [3. 0.]


### PART 5 — Try a Scaling Matrix

In [7]:
scaling_matrix = np.array([[4, 0],
                           [0, 2]])

e_vals, e_vecs = np.linalg.eig(scaling_matrix)

print("Eigenvalues:", e_vals)
print("Eigenvectors:\n", e_vecs)

Eigenvalues: [4. 2.]
Eigenvectors:
 [[1. 0.]
 [0. 1.]]


Observation:
Standard basis vectors are eigenvectors.

Because scaling stretches axes directly.

### PART 6 — Try a Rotation Matrix

In [8]:
rotation_matrix = np.array([[0, -1],
                            [1,  0]])

e_vals_rot, e_vecs_rot = np.linalg.eig(rotation_matrix)

print("Eigenvalues:", e_vals_rot)
print("Eigenvectors:\n", e_vecs_rot)

Eigenvalues: [0.+1.j 0.-1.j]
Eigenvectors:
 [[0.70710678+0.j         0.70710678-0.j        ]
 [0.        -0.70710678j 0.        +0.70710678j]]


## What Is an Eigenvector?

An eigenvector is a direction that does not change direction under a transformation.
It may stretch or shrink, but it does not rotate.

## What Is an Eigenvalue?

An eigenvalue tells us how much the eigenvector is scaled.

Large eigenvalue → strong stretching.
Small eigenvalue → weak stretching.
Negative eigenvalue → direction flips.

## Why Does This Matter in ML?

1. PCA:
   Principal components are eigenvectors of the covariance matrix.
   Largest eigenvalues correspond to directions of highest variance.

2. Stability analysis:
   Eigenvalues determine system behavior in optimization.

3. Matrix factorization:
   Many ML algorithms rely on spectral decomposition.

Eigenvalues reveal the dominant directions of structure in data.
