<a href="https://colab.research.google.com/github/aniray2908/ML-foundations-rebuild/blob/main/linear_algebra/matrix_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matrix Multiplication & Linear Transformations

Week 1 – Linear Algebra Foundations

Goal:
- Implement matrix multiplication manually
- Understand geometric meaning
- Connect matrices to ML models


In [ ]:
import numpy as np


### PART 1 — Manual Matrix Multiplication

In [ ]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)

Matrix A:
 [[1 2]
 [3 4]]

Matrix B:
 [[5 6]
 [7 8]]


In [ ]:
def manual_matrix_multiply(A, B):
    rows_A = A.shape[0]
    cols_A = A.shape[1]
    rows_B = B.shape[0]
    cols_B = B.shape[1]

    if cols_A != rows_B:
        raise ValueError("Matrix dimensions do not align for multiplication.")

    result = np.zeros((rows_A, cols_B))

    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                result[i][j] += A[i][k] * B[k][j]

    return result

In [ ]:
manual_result = manual_matrix_multiply(A, B)
numpy_result = A @ B

print("Manual Result:\n", manual_result)
print("\nNumPy Result:\n", numpy_result)


Manual Result:
 [[19. 22.]
 [43. 50.]]

NumPy Result:
 [[19 22]
 [43 50]]


### What is happening here?

Each element in the resulting matrix is:

Dot product of:
- A row from Matrix A
- A column from Matrix B

Matrix multiplication composes transformations.


### PART 2 — Geometric Interpretation

In [ ]:
v1 = np.array([1, 0])
v2 = np.array([0, 1])

print("Original v1:", v1)
print("Original v2:", v2)

Original v1: [1 0]
Original v2: [0 1]


In [ ]:
scaling_matrix = np.array([[2, 0],
                           [0, 3]])

v1_scaled = scaling_matrix @ v1
v2_scaled = scaling_matrix @ v2

print("Scaled v1:", v1_scaled)
print("Scaled v2:", v2_scaled)

Scaled v1: [2 0]
Scaled v2: [0 3]


In [ ]:
rotation_matrix = np.array([[0, -1],
                            [1,  0]])

v1_rotated = rotation_matrix @ v1
v2_rotated = rotation_matrix @ v2

print("Rotated v1:", v1_rotated)
print("Rotated v2:", v2_rotated)

Rotated v1: [0 1]
Rotated v2: [-1  0]


In [ ]:
combined_1 = rotation_matrix @ scaling_matrix
combined_2 = scaling_matrix @ rotation_matrix

print("Rotation then Scaling:\n", combined_1)
print("\nScaling then Rotation:\n", combined_2)

Rotation then Scaling:
 [[ 0 -3]
 [ 2  0]]

Scaling then Rotation:
 [[ 0 -2]
 [ 3  0]]


Matrix multiplication is NOT commutative.

AB ≠ BA

Because:
Applying transformation A then B
is different from applying B then A.

In ML:
Layer ordering changes model behavior.


## PART 3 — ML Connection

In [ ]:
# Simulating one layer of a neural network

W = np.array([[0.5, -0.2],
              [0.8,  0.1]])

x = np.array([2, 3])

output = W @ x

print("Input vector:", x)
print("Weight matrix:\n", W)
print("Layer output:", output)

Input vector: [2 3]
Weight matrix:
 [[ 0.5 -0.2]
 [ 0.8  0.1]]
Layer output: [0.4 1.9]


### Key Insights

1. A matrix represents a linear transformation.
2. Matrix multiplication composes transformations.
3. Order matters because transformations are sequential.
4. In neural networks, weights are matrices transforming inputs.
5. Every ML model layer is fundamentally matrix multiplication.
