<a href="https://colab.research.google.com/github/aniray2908/ML-foundations-rebuild/blob/main/linear_algebra/svd_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Singular Value Decomposition (SVD)

Goal:
Understand A = U Σ Vᵀ
Interpret SVD geometrically
Connect SVD to PCA


In [ ]:
import numpy as np

In [ ]:
A = np.array([[3, 1],
              [1, 3]])

print("Matrix A:\n", A)

Matrix A:
 [[3 1]
 [1 3]]


In [ ]:
U, S, Vt = np.linalg.svd(A)

print("U:\n", U)
print("\nSingular values:\n", S)
print("\nV^T:\n", Vt)

U:
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

Singular values:
 [4. 2.]

V^T:
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


In [ ]:
Sigma = np.zeros_like(A, dtype=float)
np.fill_diagonal(Sigma, S)

A_reconstructed = U @ Sigma @ Vt

print("Reconstructed A:\n", A_reconstructed)

Reconstructed A:
 [[3. 1.]
 [1. 3.]]


In [ ]:
print("Singular values:", S)

Singular values: [4. 2.]


In [ ]:
eigenvalues, _ = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)

Eigenvalues: [4. 2.]


## What is SVD?

SVD decomposes a matrix into:

A = U Σ Vᵀ

Vᵀ → rotates input space  
Σ → scales along orthogonal axes  
U → rotates output space  

So any linear transformation =
rotation → scaling → rotation

---

## Why is this powerful?

1. Works for ANY matrix (not just square).
2. Reveals intrinsic structure.
3. Foundation of PCA.
4. Used in dimensionality reduction, compression, recommendation systems.

---

## Relation to PCA

PCA can be computed using:
- Eigen decomposition of covariance matrix
OR
- Direct SVD of centered data matrix

SVD is more numerically stable.

In [ ]:
B = np.array([[1, 2, 3],
              [4, 5, 6]])

U_b, S_b, Vt_b = np.linalg.svd(B)

print("Singular values of B:", S_b)

Singular values of B: [9.508032   0.77286964]
